### ISSUE TITLE
how to pass checkpoint model from anther node. StableFast, FreeU, HyperTile?

### ISSUE THREAD

**Issue by shivshankar11** [nosiu/comfyui-instantId-faceswap#19]
i was not able to load model from any model loader.
btw can it support StableFast, FreeU, HyperTile?
i also noticed included workflow uses 90% of 24gb vram at peak, is it bug or normal vram req? maybe SBB-1B OR SEGMIND-VEGA model support can help.

**Comment by nosiu** [comment]
You cannot load a model from any other model loader. This extension uses diffusers backend and comfy ... usually does its own thing with unet, clip, and vae.

Stablefast was tested only on linux (at least readme says so) some libraries they listed are not available on windows. FreeU sounds like something highly experimental and HyperTile probably wouldn't work on this version of instantId ipadapter.
Another models? Same thing, You would need to ask the the instantid team to train new models or do it yourself.

Workflows shouldn't take so much VRAM I have no problems running it on 8GB VRAM card. It should always run with float16 precision and not float32 so your comfyui starting arguments shouldn't matter even if you are forcing it to work with float32.

Usually, SDXL models have around ~6 GB (and these were tested because of my VRAM limitations) but seeing 12 GB versions is nothing special and I bet there are even bigger ones. So I'm guessing you are loading some big model?

**Comment by shivshankar11** [comment]
can you convert ip-adapter.bin and diffuse_pytorch_model.safetensors to fp16, should reduce vram and increase perf.

**Comment by nosiu** [comment]
no longer relevant since the version update
