### ISSUE TITLE
No face detected for face embed

### ISSUE THREAD

**Issue by missevolintro** [nosiu/comfyui-instantId-faceswap#22]
Error occurred when executing FaceEmbed: No face detected for face embed
Only does it sometimes for the first FaceEmbed 1  node. 
But once it starts you have to restart comfyUI completely to get it to stop.

**Comment by nosiu** [comment]
It's a similar error to the one from readme.
`If you get No face detected in pose image error try to increase padding. It means the current mask + padding is not enough to detect the face in the input image by insightface.`

This error typically occurs when InsightFace fails to detect a face in the image connected to the face embed node (which should be highlighted in red or another distinguishable color). Since version 0.0.3, you can resolve this issue by replacing the image with another one or simply deleting the node and queuing another run.

'No face' error signifies that the embed cannot be created.

**Comment by leobridle** [comment]
I am also getting this error consistently. Increasing padding doesn't make a difference, not restarting ComfyUI. I have tried with multiple input images

**Comment by nosiu** [comment]
@leobridle padding will not help when a face embed cannot find the face. This error occurs only when preparing the face embeds. Padding works only on "pose image" it's the image where you paint the mask.

**Comment by techzuhaib** [comment]
Ideally the execution shouldn't stop, it should just bypass the face-id when no face is detected.

**Comment by nosiu** [comment]
> Ideally the execution shouldn't stop, it should just bypass the face-id when no face is detected.

considering the fact that if something doesn't work, an error should appear. It would be pretty bad if someone used 15 different nodes and 10 of them did nothing or returned default values ​​just because they were set incorrectly and the user didn't know about it.
