### ISSUE TITLE
'CrossAttentionPatch' object has no attribute 'add'

### ISSUE THREAD

**Issue by axelblaze88** [nosiu/comfyui-instantId-faceswap#57]
I get this error when i try to add an 'IPAdapter Advanced' right after the 'Apply instantId adapter' node and then straight to the ksampler.
![comfyui-instantId-faceswap-issue-1](https://github.com/user-attachments/assets/7a9cad98-310d-4036-bd58-fbe408b02d55)

**Comment by nosiu** [comment]
instantid adapter and ipadapter are basically the same technology so both plugins will not work together. If you reversed the order and want to send the model from "ipadapter advance" to "apply instantId adapter" you would probably get the error 'Attn2Replace' object has no attribute 'set_new_condition' (I guess looking at the IpAdapter plus code).

This is because both adapters operate on the same layers.

InstantId adapter does not play such a big role (if I remember correctly I put a link showing that the adapter itself does not play a big role in the readme) the power of instantId is based mainly on ControlNet so I suggest removing the "apply instantId adapter" node and just use the Controlnet. You still need to load instantId adapter to prepare embeds for ControlNet but it should do the trick.

**Comment by nosiu** [comment]
There are a few ways to improve results if you have a problem with blending the final result into the picture then I suggest using fooocus inpaint  (comfyui-inpaint-nodes), 

if you have a problem with a face shape and the position of the eyes/nose/mouth and shape of a face then I suggest using ComfyUI_FaceShaper to change the position of eyes, nose, and all that stuff before you draw a mask,  it may look complex but it isn't.

I didn't want to include third-party nodes in workflows to demonstrate all of hose but it's hinted in #Tips sections
